kys0411/recipe_project

build.gradle
src/main/java/ingredient/domain/Ingredient.java
src/main/java/like/domain/Like.java
src/main/java/recipe/constant/Category.java
src/main/java/recipe/constant/Difficulty.java
src/main/java/recipe/domain/Ingredient.java
src/main/java/recipe/domain/Recipe.java
src/main/java/review/domain/Review.java
src/main/java/user/constant/Role.java
src/main/java/user/domain/User.java

- #1
-  recipe, ingredient 등.. 도메인 코드 생성했습니다!
- 테이블 컬럼명과 도메인 속성 이름이 다른게 몇가지 있는데 어떤게 더 적절할지 봐주시면 감사하겠습니다!

[Feature-1] 도메인 코드 생성

---

build.gradle
src/test/java/JDBCTest.java

test:  jdbc 설정 연결 테스트

---

src/main/java/recipe/constant/Category.java
src/main/java/recipe/constant/Difficulty.java
src/main/java/recipe/domain/Recipe.java
src/main/java/recipe/service/RecipeService.java
src/test/java/recipe/create/RecipeCreateTest.java

- #13 
- 기존의 조리과정, 재료 배열을 Temp 테이블을 거쳐 프로시저에 대입하는 것을
Java의 Object 객체를 통해 대입 하는 코드로 수정
```java
public void getCreateTestResult(Recipe recipe, Object[][] stepsData, Object[][] ingredientsData, Connection conn) throws SQLException {
// DB에서 CREATE OR REPLACE TYPE으로 만들어 둔 STEP_TAB라는 Oracle 배열 타입 가져오기
ArrayDescriptor stepDesc = ArrayDescriptor.createDescriptor("STEP_TAB", conn); 
ARRAY stepsArray = new ARRAY(stepDesc, conn, stepsData); // 오라클 배열 실제 인스턴스
ArrayDescriptor ingredientDesc = ArrayDescriptor.createDescriptor("INGREDIENT_TAB", conn);
ARRAY ingredientsArray = new ARRAY(ingredientDesc, conn, ingredientsData);
...
``` 
- 레시피 도메인 및 Enum Type 수정
- 레시피 조회 시 Enum 타입 비교가 필요할 것 같아 비교 Enum 클래스에 메소드 만들어 뒀는데 더 나은 방법이 있을까요??
- 테스트 메소드 이름 및 클래스 명이 좀 저 좋은 명칭이 있을까요??

[Feature-#13] 레시피 생성 코드 및 레시피 도메인 및 Enum Type 수정

---

src/main/java/recipe/service/IngredientCombinationService.java
src/main/java/recipe/service/IngredientUtilizationRecipeService.java
src/test/java/recipe/combination/recipeCombinationTest.java

- #8 
- 배열 타입으로 식재료를 입력받아 해당하는 식재료로 만든 레시피 조회 작업 및 테스트
- 검색한 식재료가 많이 들어간 레시피를 기준으로 내림차순 정렬 했습니다.

[Feature-8] 식재료 활용 레시피 검색 기능 추가

---

build.gradle
src/main/java/common/DBConnection.java
src/main/java/recipe/domain/Recipe.java
src/main/java/recipe/repository/RecipeRepository.java
src/main/java/recipe/service/CreateRecipeService.java
src/test/java/recipe/create/RecipeCreateTest.java
src/test/java/recipe/repository/RecipeRepositoryTest.java

- #7 
- 레시피 생성 로직을 구현하였습니다
- 레시피 도메인 속성을 수정하였는데 괜찮을까요? (Object[][] ingredients, Object[][] steps)

[Feature-7] 레시피 생성 로직 구현

---

src/main/java/user/DBConnection.java
src/main/java/user/constant/Role.java
src/main/java/user/domain/User.java
src/main/java/user/dto/UserjoinRequestDto.java
src/main/java/user/service/UserService.java
src/test/java/user/service/UserServiceTest.java

- #9
회원 가입 서비스 로직을 구현했습니다.
- 내용

[Feature-9] 회원가입

---

src/main/java/recipe/repository/RecipeQueryRepository.java
src/main/java/recipe/service/FindRecipeService.java
src/test/java/recipe/repository/RecipeQueryRepositoryTest.java

- #22 
- 레시피 상세조회 기능을 구현하였습니다..
- 레시피 생성 로직에서 레시피 id를 반환하도록 수정한 후에 테스트 코드 고쳐보겠습니다ㅠ!

[Feature-22] 레시피 상세 조회 기능 추가

---

src/main/java/user/constant/Role.java
src/main/java/user/service/UserService.java
src/test/java/user/service/UserServiceTest.java

[Feature-16] 회원 조회 기능

---

src/main/java/like/constant/Status.java
src/main/java/like/domain/Like.java
src/main/java/like/repository/LikeQueryRepository.java
src/main/java/like/repository/LikeRepository.java
src/main/java/like/service/FindLikeRecipeService.java
src/main/java/like/service/UpsertLikeService.java
src/main/java/recipe/repository/RecipeQueryRepository.java
src/test/java/recipe/repository/like/LikeQueryRepositoryTest.java
src/test/java/recipe/repository/like/LikeRepositoryTest.java
src/test/java/recipe/repository/recipe/RecipeQueryRepositoryTest.java
src/test/java/recipe/repository/recipe/RecipeRepositoryTest.java

- #25 
- 좋아요 기능 추가 service, repo
- like 빌더패턴 적용 및 status 타입 변경
- test 패키지 구조 수정
- 좋아요 조건 비교(좋아요 한거면 status를 0, 안한거면 1로 update)는 프로시저에서 해줬습니다!

Feature/#25 좋아요 기능 추가 및 테스트 패키지 구조 수정

---

src/main/java/RecipeProject.java
src/main/java/review/Controller/ReviewController.java
src/main/java/review/domain/Review.java
src/main/java/review/impl/ReviewDaoImpl.java
src/main/resources/fxml/RecipeReview.fxml

- #32 
-  레시피 프로그램 종료 UI/UX 수정
- 사용자가 추천한 점수만큼 별 개수 시각화 표기
- CheckBox 전체선택, 부분선택 이벤트 기능
- 내용

[Feature-32]리뷰후기 추천점수 시각화,체크박스 선택 이벤트 작업

---

src/main/java/recipe/dto/RecipeDto.java
src/main/java/recipe/repository/Condition.java
src/main/java/recipe/repository/RecipeQueryRepository.java

- #18 
- 레시피 정렬기능을 추가하였습니다
- 좋아요순, 후기순, 별점순에 따른 정렬을 구현하였습니다😉
- 정렬 기능을 테스트할 괜찮은 방법이 있을까요?.?

[Feature-18] 레시피 정렬 기능 추가

---

src/main/java/review/Controller/ReviewController.java
src/main/java/review/Dao/ReviewDao.java
src/main/java/review/impl/ReviewDaoImpl.java
src/main/java/review/impl/ReviewServiceImpl.java
src/main/java/review/service/ReviewService.java
src/main/resources/fxml/RecipeReview.fxml

- #37 
- 레시피 후기 CheckBox 전체, 선택 삭제, 삭제 후 목록 리프레시
- 내용

[Feature] 레시피 후기 CheckBox 전체, 선택 삭제, 리프레시

---

src/main/java/RecipeProject.java
src/main/java/review/Controller/ReviewController.java
src/main/java/user/controller/LoginController.java
src/main/java/user/controller/RegisterController.java
src/main/resources/fxml/login.fxml
src/main/resources/fxml/register.fxml

[Feature-10] 로그인 페이지

---

src/main/java/RecipeProject.java
src/main/java/common/MainController.java
src/main/java/review/Controller/ReviewController.java
src/main/java/review/Controller/ReviewDetailController.java
src/main/java/review/Controller/UI.java
src/main/java/review/impl/ReviewDaoImpl.java
src/main/java/review/service/ReviewService.java
src/main/resources/fxml/DetailMemberReview.fxml
src/main/resources/fxml/Main.fxml
src/main/resources/fxml/RecipeReview.fxml
src/main/resources/fxml/insertRecipeReview.fxml
src/main/resources/fxml/updatetRecipeReview.fxml

[Feature-45] 메인화면, 리뷰상세조회 작업

---

src/main/java/recipe/controller/CreateRecipeController.java
src/main/java/recipe/controller/RecipeController.java
src/main/resources/fxml/createRecipe.fxml

- #40
- 레시피 생성 controller와 fxml파일을 추가하였습니다.

[Feature-40] 레시피 생성 ui 추가

---

src/main/java/RecipeProject.java
src/main/java/review/Controller/ReviewController.java
src/main/resources/fxml/Main.fxml
src/main/resources/fxml/RecipeReview.fxml

- #48 
- 어플리케이션 크기 조정, 메인에서 버튼 클릭하여 다른화면 이동시 UX 통일
- 내용

[Feature-48]어플리케이션 UX 조정

---

src/main/java/RecipeProject.java
src/main/java/common/MainController.java
src/main/java/review/Controller/ReviewController.java
src/main/java/user/controller/LoginController.java
src/main/resources/fxml/Main.fxml

- #47 
- 로그아웃
- 처음페이지 로그인 화면으로 변경

[Feature-47] 로그아웃 처리

---

src/main/java/common/MainController.java
src/main/java/recipe/controller/RecipeController.java
src/main/resources/fxml/Main.fxml

- #52 
- 메인화면 레시피생성 버튼 추가하여 화면연결
- 내용

[Feature-52]메인화면 레시피생성 버튼 추가하여 화면연결

---

src/main/java/user/controller/MyInfoController.java
src/main/resources/fxml/myInfo.fxml

[Feature-53] 회원 상세페이지

---

src/main/java/user/controller/MyInfoController.java
src/main/java/user/controller/UserUpdateController.java
src/main/java/user/dto/UserUpdateRequestDto.java
src/main/java/user/service/UserService.java
src/main/resources/fxml/myInfo.fxml
src/main/resources/fxml/userupdate.fxml
src/test/java/user/service/UserServiceTest.java

[Feature-58] 회원 수정 기능 및 화면

---

src/main/java/recipe/controller/CreateRecipeController.java
src/main/java/recipe/repository/RecipeRepository.java

- #61 
- 레시피가 생성되게 수정
- CreateRecipeController의 step, ingredient 배열 생성 방법 수정
- 내용

[refactor-61] : fxml을 통한 레시피 생성 기능 수정

---

src/main/java/recipe/controller/CreateRecipeController.java

- #64 
- 레시피 생성 후 메시지 띄우고 메인페이지로 넘기기

[Feature-64] 레시피 생성 수정

---

src/main/java/RecipeProject.java
src/main/java/review/Controller/ReviewController.java
src/main/java/review/Controller/ReviewDetailController.java
src/main/java/review/Controller/UI.java
src/main/java/review/Dao/ReviewDao.java
src/main/java/review/impl/ReviewDaoImpl.java
src/main/java/review/impl/ReviewServiceImpl.java
src/main/java/review/service/ReviewService.java
src/main/resources/fxml/DetailMemberReview.fxml
src/main/resources/fxml/RecipeReview.fxml

- #52 
- 메인 레시피 생성 버튼 추가
- 레시피 후기 전체 후기 조회
- 레시피 후기 내 후기 조회
- 내용

[Feature-52]메인화면 레시피 생성, 레시피 후기 조회(전체/사용자)

---

src/main/java/recipe/controller/GetAllRecipesController.java
src/main/java/recipe/dto/RecipeDto.java
src/main/java/recipe/repository/Condition.java
src/main/java/recipe/service/GetAllRecipesService.java
src/main/resources/fxml/getAllRecipes.fxml

[Feature-57] 레시피 정렬 ui 추가

---

src/main/java/recipe/repository/RecipeQueryRepository.java
src/main/java/recipe/service/FindRecipeService.java

- #69
-  레시피 검색 기능을 구현하였습니다
- 단순히 제목으로 검색해도 괜찮을까요?.?

[Feature-69] 레시피 검색 기능 추가

---

src/main/java/common/MainController.java

- #71 
- 메인페이지 레시피 조회 페이지 경로 수정

[Feature-71]메인페이지 레시피 조회 페이지 경로 수정

---

src/main/java/recipe/controller/GetAllRecipesController.java
src/main/java/recipe/repository/RecipeQueryRepository.java
src/main/resources/fxml/getAllRecipes.fxml

- #73
- 레시피 검색 ui를 구현하였습니다
- 레시피 리스트 ui는 따로 pr 올리겠습니다~..

[Feature-73] 레시피 검색 ui 추가

---

src/main/java/recipe/controller/ingredientCombinationController.java
src/main/resources/fxml/ingredientCombination.fxml

- #78
- 식재료 조합 레시피 목록 조회 UI 구현

feature/#78 :  식재료 조합 레시피 목록 조회 UI 구현

---

src/main/java/user/controller/MyInfoController.java
src/main/resources/fxml/myInfo.fxml

[Feature-82]마이페이지 수정

---

src/main/java/recipe/controller/GetAllRecipesController.java
src/main/java/recipe/controller/RecipeController.java

[Feature-84] 레시피 상세조회 화면 연결

---

src/main/java/recipe/controller/ingredientCombinationController.java
src/main/java/recipe/repository/RecipeSelectRepository.java
src/main/resources/fxml/ingredientCombination.fxml

- #78 
-  식재료 조합 레시피 목록 조회 UI 수정 
- 내용

[Feature-78] 식재료 조합 레시피 목록 조회 UI 수정 

---

README.md

Project Reademe 작성
- Project Reademe 작성
- Reademe 작성

docs : Project Reademe 작성

---

src/main/java/common/MainController.java
src/main/java/recipe/controller/RecipeController.java
src/main/java/recipe/controller/ingredientCombinationController.java
src/main/resources/fxml/Main.fxml

- #88 
- 식재료 조합 레시피 목록 조회 구현으로 인한 수정

refactor/#88 : 식재료 조합 레시피 목록 조회 구현으로 인한 수정
